### ISSUE TITLE
Some Enhancements  requested

### ISSUE THREAD

**Issue by sajalnew** [archerysec/archerysec#290] opened 2019-05-10 16:17 UTC
Github Repo scanning via trufflehog
Authenticated scans via owasp zap and arachani when using docker 
Static code analysis of ruby applications via brakeman and dawnscanner

**Comment by anandtiwarics** [comment] 2020-05-08 14:56
Duplicate of #18

**Closed by anandtiwarics** 2020-05-08 14:56 UTC

**Comment by anandtiwarics** [comment] 2020-05-08 14:57
Duplicate of #16
