### ISSUE TITLE
Custom Tools and Plugins

### ISSUE THREAD

**Issue by rams3sh** [archerysec/archerysec#107] opened 2018-12-31 04:15 UTC
It would be great if you could make a framework around addition of custom tools and custom parser for each tool to be added as a separate plugin within Archery something like ola jackhammer. Reference link given below :-

https://jch.olacabs.com/userguide/adding_new_tool/

This would help us to enhance the framework easily module by module.

**Comment by wheelq** [comment] 2019-04-05 11:11
+ nmap
+ wapiti etc...

**Comment by anandtiwarics** [comment] 2020-05-08 17:29
Duplicate of #16

**Closed by anandtiwarics** 2020-05-08 17:29 UTC
