### ISSUE TITLE
Add Nexpose in Scanners parser & Plugin

### ISSUE THREAD

**Issue by NRGLine4Sec** [archerysec/archerysec#138] opened 2019-03-29 15:53 UTC
Can you add Nexpose in Scanners parser & Plugin ?

**Comment by mich4e1** [comment] 2019-07-04 04:47
The same question is interested, how to add integration with Nexpose and/or Qualys (or import XML)?

**Comment by anandtiwarics** [comment] 2019-07-04 05:08
Could you please send us a report sample in XML format for both Qualys and Nexpose?

**Comment by mich4e1** [comment] 2019-07-04 07:49
> Could you please send us a report sample in XML format for both Qualys and Nexpose?

At the moment work on it. Once I have the report with share here.

**Comment by zorianix** [comment] 2020-04-01 22:38
Hi Anand I would like to contribute to the project by adding plugin support like qualys , nexpose , can you let me know how can i contribute

**Comment by anandtiwarics** [comment] 2020-05-08 17:29
Duplicate of #16

**Closed by anandtiwarics** 2020-05-08 17:29 UTC
